### ISSUE TITLE
Disagreement between docs and implementation on name of pool timeout parameter

### ISSUE THREAD

**Issue by jackfirth** [greghendershott/http#11]
The parameter for controlling the connection pool timeout in seconds is documented under the name `connection-pool-timeout`, but implemented and provided under the name `current-pool-timeout`.

**Comment by greghendershott** [comment]
Thanks for pointing this out! (The rendered docs didn't show the usual red underline for this, so I never noticed the mistake.)

**Comment by jackfirth** [comment]
I think the red underline only shows for identifiers that don't have a `for-label` import of the module they're documented to belong to - whether or not the module imported `for-label` actually _provides_ those identifiers is irrelevant. You can document things in a module that don't actually exist without any issues AFAIK.

Anyway, thanks for the fast fix!
