### ISSUE TITLE
request tests failing

### ISSUE THREAD

**Issue by samth** [greghendershott/http#12]
Currently the tests for http/request are failing in DrDr: http://drdr.racket-lang.org/60508/racket/share/pkgs/http/http/request.rkt

Running this locally it usually fails in the same way. With `PLTSTDERR=info@http`, I get output like this before it hangs:

```
http: === Testing with current-pool-timeout = 0
http: http://www.racket-lang.org
http:   get-twice
http:   call/input-request, no encoding
http:   call/input-request, gzip,deflate
http: http://www.httpwatch.com/httpgallery/chunked/
http:   get-twice
http:   call/input-request, no encoding
http:   call/input-request, gzip,deflate
http: http://www.google.com/
http:   get-twice
http:   call/input-request, no encoding
http:   call/input-request, gzip,deflate
http: https://www.google.com/
http:   get-twice
http:   call/input-request, no encoding
http:   call/input-request, gzip,deflate
http: http://www.wikipedia.org
http:   get-twice
http:   call/input-request, no encoding
http:   call/input-request, gzip,deflate
http: http://www.audiotechnica.com
http:   get-twice
http:   call/input-request, no encoding
http:   call/input-request, gzip,deflate
http: http://www.microsoft.com/
http:   get-twice
http:   call/input-request, no encoding
http:   call/input-request, gzip,deflate
```

I think this suggests that the connection to `http://www.microsoft.com/` is hanging but I'm not certain. Sometimes it works, and sometimes it hangs in the `current-pool-timeout = 10` section, at the same place.

Nothing seems to have changed in Racket right at the time that this happened.

**Comment by greghendershott** [comment]
It fails for me locally, too.

My first thought was some http->https redirect problem -- which might indicate a bug to fix on my end. But when I change  `http://www.microsoft.com/` to `https://www.microsoft.com/`, it still hangs.

Only deleting `www.microsoft.com` from the list of sites to test, "works". This suggests (to me) that they started doing some "old-fashioned" "anti-scraping" thing (perhaps based on the user agent string being sent).

I think that might be interesting to investigate. Meanwhile I think it would be good simply to delete `microsoft.com` from the list of sites used in the tests (even if that doesn't necessarily "close" this issue).

**Comment by greghendershott** [comment]
I merged a commit to remove `microsoft.com` from the list of test sites.

I'll try to investigate more, to determine if that's a genuine solution or just a temporary mitigation.

**Comment by greghendershott** [comment]
I did some more investigating, including trying other HTTP clients.

Although I'm not 100.0% sure, I think the problem was that Akamai was behaving like this in the face of there being no `User-Agent` request header.

So I think something like commit 3f3f930 is more like a real fix: If the user's request headers don't include a `User-Agent`, automatically add one with the value `"Racket https://github.com/greghendershott/http"`.

I might sleep on this before merging....

**Comment by greghendershott** [comment]
From looking at the example of the `http-client` library as well as [the spec](https://httpwg.org/specs/rfc7231.html#header.user-agent) I think a better default `User-Agent` value would be:

```racket
(define default-user-agent (format "Racket/~a (http package)" (version)))
```

That's the only change in the commit 4d03fb6 I just force-pushed.

Sleeping a bit more before merging....
